### ISSUE TITLE
Go to begin and end of buffers with beginend

### ISSUE THREAD

**Issue by DamienCassou** [Fuco1/Fuco1.github.io#1]
You might want to use my beginend package (https://github.com/DamienCassou/beginend) for Emacs.

**Comment by Fuco1** [comment]
Good touch with the minor modes, that's probably better appraoch than global redefinitions.

Some of the functions you use seem rather complicated but I think the basic setup is rather similar to my approach. Maybe we could add some macros to simplify the setup?  Your library doesn't provide much framework for the end-user, they still have to define 3 to 4 functions.

**Comment by DamienCassou** [comment]
Feel free to contribute whatever you seem necessary. I agree we could do better. Do you want write access?
