### ISSUE TITLE
Org-gcal-header-alist

### ISSUE THREAD

**Issue by JSpenced** [Fuco1/Fuco1.github.io#16]
Where is this defined to get the entries the color you want? I don't see it in org-gcal.

**Comment by Fuco1** [comment]
The `org-gcal-header-alist` is defined in `org-gcal`.  The colors setup is for my package https://github.com/Fuco1/org-timeline

**Comment by JSpenced** [comment]
I really don't see `org-gcal-header-alist` defined or referenced anywhere in org-gcal. I like the timeline so added that but it comes out as blue not pink.

**Comment by Fuco1** [comment]
There's multiple version of org-gcal around, one was abandoned and another was forked.  I'm using this version: https://github.com/kidd/org-gcal.el

Seems like the setting was actually removed: https://github.com/kidd/org-gcal.el/pull/34/files#diff-f827da7b7cb5648ae3e2443135e51551L109

Just another reason to never upgrade :D If you figure it out let me know!

**Comment by JSpenced** [comment]
Yeah, it isn't essential for my setup, but I have a newer version of the
kidd repo from melpa.

I just wrote something to highlight the file at the beginning that it comes
from so works across all my files.
